hswebapp/auth.py
from flask import Blueprint,render_template,flash, redirect, url_for, request, Response, jsonify
from jinja2 import TemplateNotFound
from hswebapp import app,db
from importlib import import_module
import os
from flask_login import login_required,login_user,logout_user, current_user
from datetime import datetime
from time import sleep
from hswebapp.forms.hswforms import LoginForm,RegisterForm,EditUserForm
from hswebapp.models.system_models import User,Logs,AccessGroup
import copy
from datetime import datetime
from sqlalchemy.exc import IntegrityError
from hswebapp.models.hsutil import Hsutil

webapp_auth = Blueprint('webapp_auth', __name__,template_folder='templates/auth/pages')
@webapp_auth.route('/register', methods=['GET','POST'])

def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
                
        try:
            new_user = User(username=form.username.data,email=form.email.data,lastlogin=datetime.now())
            new_user.set_password(new_password=form.password.data)
            db.session.add(new_user)
            db.session.commit()
            
        except IntegrityError as e:
            db.session.rollback()
            flash('The user: {} or the email {} already exists \n Thank you'.format(form.username.data,form.email.data))
            app.logger.error('Sign up error: {}'.format(e))
            return render_template("hsw_signup.html",form = form)
        
        except Exception as e:
            app.logger.error('Sign up error: {}'.format(e))
            db.session.rollback()
            flash('Error! Sorry for the inconvinience The issue has been logged and it will be solved asap')
            return render_template("hsw_signup.html",form = form)
        
        finally:
            db.session.close()
    
                         
        flash('The user: {} has been created'.format(form.username.data))                
        return redirect(url_for('webapp_auth.login'))
        
    return render_template("hsw_signup.html",form = form)

@webapp_auth.route('/login', methods=['GET','POST'] )
def login():
    form = LoginForm()
    if form.validate_on_submit():
    
        try:    
            user = User.query.filter_by(username=form.username.data).first()
        
        
            if (user):
                if  user.check_password(check_password=form.password.data):
                    user.lastlogin = datetime.now()
                    db.session.commit()
                
                    login_user(user,remember=form.rememberme.data)
                    
                    log = Logs(user_id= user.id,operation='login',origin='webapp')
                    db.session.add(log)
                    db.session.commit()
                    
                    #TODO IMPLEMENT REDIRECT GET THE NEXT
                    #next = request.args.get('next')
                    #if not is_safe_url(nextform):
                    #    return flask.abort(400)
                    #http://flask.pocoo.org/snippets/62/
                    #return redirect(url_for(next))
                    next_page = request.args.get('next')
                    #flash(next_page) none 
                    if not next_page or not next_page.startswith('/'):
                        next_page=url_for('views.home')
                    return redirect(next_page)
                    
                    
                    #return redirect(url_for('views.home'))
                            
                flash('Invalid password')
                return render_template("hsw_login.html",form = form)
            flash('User does not exist')
            return render_template("hsw_login.html",form = form)
    
        except:
            flash("InvalidRequestError: {} ".format(sys.exc_info()[0]))
        
            raise
            db.session.rollback()
            return redirect(url_for('home'))
        
        finally:
            db.session.close()
    
    return render_template("hsw_login.html",form = form)

@webapp_auth.route('/logout')
@login_required
def logout():
    ## fix the null problem log out
    #shallow copy copy.copy(current_user.id)
    user= copy.copy(current_user)
    logout_user()
    flash("See ya: {}".format(user.username))
    log = Logs(user_id= user.id,operation='logout',origin='webapp')
    db.session.add(log)
    db.session.commit() 
    return redirect(url_for('views.home'))

@webapp_auth.route('/logs')
@login_required
def user_logs():
    
    try:
        users= User.query.all()
    except:
        raise
        db.session.rollback()
    
    #finally:  does not show the logs detail
    #    db.session.close()
    
    return render_template("logs_stats.html", users=users)
    

@webapp_auth.route('/users', methods=['GET'])
def show_users():
# http://flask-sqlalchemy.pocoo.org/2.3/api/   check flask_sqlalchemy.Pagination 
    page_num = request.args.get('page_num',1,type=int)
    
    users = User.query.paginate(per_page=3, page=page_num, error_out=True)

    return render_template('system_users.html', users=users)    

@webapp_auth.route('/edit_user', methods=['GET','POST'] )
@login_required
def edit_user():
    
    form = EditUserForm(obj=current_user)
    form.acess_group.choices = [(g.id, g.description) for g in AccessGroup.query.order_by('id')]
        
        
    if (request.method == 'POST' and form.validate_on_submit()==True):
        
        form.populate_obj(current_user) 
        db.session.commit()
        
        flash('Your change(s) has(have) been saved ')
        return redirect(url_for('webapp_auth.edit_user'))
    db.session.close()  ## close the session on update page problems  
    return render_template('edit_user.html', form=form,hsutil=Hsutil)
        
  
@webapp_auth.route('/delete_user', methods=['GET','POST'] )
@login_required
def delete_user():
    
    user_id=request.form['user_id']
    
#    user_id = request.args.get('user_id',0,type=int)
    user = User.query.get(user_id)
    if not user :  
        return jsonify({'result' : 'error','message':'User not provided'})
    
    
    if (user.logs.count() == 0):
        db.session.delete(user) # todo check for constraint 
        db.session.commit()
    else :
        
        user.deleted_on=datetime.utcnow()
        #db.session.add(user)
        db.session.commit()
        
    return jsonify({'result' : 'success', 'message' :'user deleted' })
        
@webapp_auth.route('/update_user', methods=['POST'])
@login_required
def update_user():
    app.logger.info('updating user')
    updated=datetime.now()
    try:
        user = User.query.filter_by(id=request.form['id']).first()
        user.username = request.form['username']
        user.email = request.form['email']
        user.updatedAt = updated
        
        db.session.commit()
        
    
    except Exception as e:
        app.logger.error('Update error: {}'.format(e))
        db.session.rollback()
        flash('Error! Sorry for the inconvinience The issue has been logged and it will be solved asap') 
        return jsonify({'result' : 'error'})
    
    finally:
        db.session.close()
        
    return jsonify({'result' : 'success', 'updated' :updated })

    

hswebapp/views.py
from flask import Blueprint,render_template,flash, redirect, url_for, request, \
                  Response,Flask,jsonify,session
from jinja2 import TemplateNotFound
from hswebapp import app,db,login_manager,model_saved,celery
from hswebapp.models.sensor_models import TempLog,HumidityLog,PressureLog,PowerLog,EventLog
from hswebapp.models.resources import sensorlog_schema,powerlog_schema,templog_schema
from datetime import datetime
#testing 
from random import randint

from flask_mail import Mail,Message
mail = Mail(app)

#from sqlalchemy.exc import IntegrityError
from flask_login import login_required,login_user,logout_user, current_user
from hswebapp.models.system_models import User

#####
import requests
import json

views = Blueprint('views', __name__,template_folder='templates')


def add_event(message):
    return message
   
    
@views.route('/')
def home():
    return render_template('pages/home.html')


@views.route("/environment")
@login_required
def dashboard():
    import sys
    
    try:                       
        temperature_sensor1= TempLog.query.order_by(TempLog.rdate.desc()).filter_by(sensorType='AM2302').first()          
        temperature_sensor2= TempLog.query.order_by(TempLog.rdate.desc()).filter_by(sensorType='DH11').first()                        
        temperature_sensor3= TempLog.query.order_by(TempLog.rdate.desc()).filter_by(sensorType='BMP180').first()
                      
        humidity_sensor1= HumidityLog.query.order_by(HumidityLog.rdate.desc()).filter_by(sensorType='AM2302').first()     
        humidity_sensor2= HumidityLog.query.order_by(HumidityLog.rdate.desc()).filter_by(sensorType='DH11').first()        
                        
        pressure_sensor1= PressureLog.query.order_by(PressureLog.rdate.desc()).first()
            
        power_sensor1 =   PowerLog.query.order_by(PowerLog.rdate.desc()).first()                     
                       
    except:
        flash("InvalidRequestError: {} ".format(sys.exc_info()[0]))
        
        raise
        db.session.rollback()
        return redirect(url_for('home'))
    finally:
        db.session.close()
     
    
    return render_template("pages/dashboard.html",temperature_sensor1=temperature_sensor1,
                                temperature_sensor2=temperature_sensor2,
                                temperature_sensor3=temperature_sensor3,
                                humidity_sensor1=humidity_sensor1,
                                humidity_sensor2=humidity_sensor2,
                                pressure_sensor1=pressure_sensor1,
                                power_sensor1=power_sensor1,
                                TempLog=TempLog,
                                HumidityLog=HumidityLog,
                                PressureLog=PressureLog,
                                PowerLog=PowerLog
                                )
  
        
@views.route('/readings', methods=["GET"])
@login_required
def report_listreadings():
    try:
        temperature = TempLog.query.order_by(TempLog.rdate.desc()).limit(50).all()
        humidity = HumidityLog.query.order_by(HumidityLog.rdate.desc()).limit(50).all()
        pressure = PressureLog.query.order_by(PressureLog.rdate.desc()).limit(50).all()
        power = PowerLog.query.order_by(PowerLog.rdate.desc()).limit(50).all()
    
    except:
        flash("InvalidRequestError: {} ".format(sys.exc_info()[0]))
        
        raise
        db.session.rollback()
        return redirect(url_for('home'))
    finally:
        db.session.close()
        
   
    return render_template("readings.html", temperature = temperature,humidity =humidity, pressure = pressure, power = power)
               

@views.route('/grafics', methods=["GET"])
def report_grafics():
    import sys
    try:
        result=TempLog.query.count()
        templog= TempLog.query.order_by(TempLog.rdate.desc()).limit(10).all()
        humiditylog= HumidityLog.query.order_by(HumidityLog.rdate.desc()).limit(10).all()
        pressurelog= PressureLog.query.order_by(PressureLog.rdate.desc()).limit(10).all()
        powerlog =   PowerLog.query.order_by(PowerLog.rdate.desc()).limit(10).all()
        
        
    except:
        app.logger.error("InvalidRequestError: {} ".format(sys.exc_info()[0]))
        
        raise
        db.session.rollback()
        return redirect(url_for('home'))
    finally:
        db.session.close()
        
        
    return render_template("pages/grafics.html",ntemp=result,
                                temp = templog,
                                humididylog= humiditylog,
                                pressurelog=pressurelog,
                                powerlog=powerlog
                                )
   
    
@views.route('/about1', methods=["GET"])
@login_required
def about1():
    return render_template("pages/about.html")

@app.errorhandler(404)
def page_not_found(e):
    return render_template("errors/404.html"),404

    
@model_saved.connect
def model_saved_signal(app, message, **extra):
#check what page/template is beind rendered
    
    try:
        event=EventLog(ob_id=message.get_id(), ob_type=message.get_type())
        event.save_to_db()
    
    except Exception as e:
        app.logger.error('Update error: {}'.format(e))
        db.session.rollback()
    
    finally:
        db.session.close()
    
 
@views.route('/update_dashboard', methods=['POST'])
@login_required
def update_dashboard():
      
    page_load=(request.form['page_load']) 
    
    fmt="YYYY-mm-ddTHH:MM:SS.SSSZ"
    py_format='YYYY-MM-DDTHH:MM:SS'    
    jsdate=datetime.strptime(page_load, '%Y-%m-%dT%H:%M:%S.%fZ')
        
    #ValueError: time data '2017-12-17T20:46:23.438Z' does not match format 'YYYY-MM-DDTHH:MM:SS'
    #datetime_object = datetime.strptime(page_load,py_format)
    #print('##############date###################')
    #print(jsdate)
    #print('##############date###################')        
    #now_utc = datetime.now(timezone('UTC'))
    
    try:
        if  (EventLog.query.count()==0) :
            return jsonify({'result' : 'no_data','last_Attempt': datetime.now()})
        else: 
            event = EventLog.query.order_by(EventLog.id.asc()).first()
        
        
    except:
        app.logger.error("InvalidRequestError: {} ".format(sys.exc_info()[0]))
        
        raise
        db.session.rollback()
        return jsonify({'result' : 'no_data','last_Attempt': datetime.now()})
    
            
    if (event.ob_type=='TempLog'):
        updated=TempLog.query.filter_by(id=event.ob_id).first()
      
    elif (event.ob_type=='HumidityLog'):
        updated=HumidityLog.query.filter_by(id=event.ob_id).first()   
    elif (event.ob_type=='PressureLog'):
        updated=PressureLog.query.filter_by(id=event.ob_id).first()   
    elif (event.ob_type=='PowerLog'):
        updated=PowerLog.query.filter_by(id=event.ob_id).first() 
    
    event.delete_from_db()  

    if (type(updated) is PowerLog):
        result = powerlog_schema.dump(updated)
        return powerlog_schema.jsonify(updated)
    else :
        result = sensorlog_schema.dump(updated)
        #pprint(result)
        return sensorlog_schema.jsonify(updated)
        

@views.route('/update_event', methods=['POST'])
@login_required
def dashboard_event():
    pass    
# retreive the the time that the page has been loaded and return the next event_id to be refreshed



@views.route('/exporting_templog')
@login_required
def exporting():
    
    #op = randint(0,1)
    sensor_type = request.args.get('sensor_type', 'PressureLog', type=str)
    sensor_class = globals()[sensor_type]     
        
        
    try:
        
       
        log = sensor_class.query.with_for_update().filter(sensor_class.exported.is_(None)).order_by(sensor_class.rdate.desc()).first()
               
            
        if (log is None): 
            return jsonify({'message':'no_data'}),204
        else :
            mdata= templog_schema.dump(log).data
    
    except Exception as e:
        app.logger.error('Error reading bd : {}'.format(e))
        db.session.rollback()
    
    finally:
        db.session.close()
    
    
    headers = {'Content-type': 'application/json', 'Accept': 'application/json'}
    #r = requests.post('https://dev.hswebapp.com/api/templog', data = {'key':'value'})    
    my_request = requests.post('https://dev.hswebapp.com/api/templog?sensor_type='+sensor_type,json=mdata,headers=headers)              
    
    if (my_request.status_code == 201 or my_request.status_code == 409):
        log.exported = datetime.utcnow()
        db.session.add(log)
        db.session.commit()
    
    
    
    #print(my_request.status_code)
    print(my_request.json())
    if (my_request.status_code != 201 ):
        return jsonify(my_request.json()),my_request.status_code
    
    return jsonify(my_request.json()),201

@views.route('/export')
@login_required
def export(): 
    
    return render_template('pages/export.html',TempLog=TempLog,HumidityLog=HumidityLog,PressureLog=PressureLog)
   
   
   
@views.route('/test99')
@login_required
def send_mail():
    
    
    session['email'] = 'hoascv@gmail.com'
    
    # send the email
    msg = Message('Hello from Flask',sender='hsupp99@gmail.com',
                  recipients=['hoascv@gmail.com'])
    msg.body = 'This is a test email sent from a background Celery task.'
    send_async_email.delay(msg)
    return redirect(url_for('home'))    
@celery.task
def send_async_email(msg):
    """Background task to send an email with Flask-Mail."""
    with app.app_context():
        mail.send(msg)


        


    

hswebapp/templates/layout/base.html
<!doctype html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>

<!-- meta -->

{% block meta %}
<meta name="description" content="">
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}
<!-- /meta -->

<!-- styles -->
{% block styles %}
<link type="text/css" rel="stylesheet" href="/static/css/font-awesome-4.1.0.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-3.1.1.min.css">
<link type="text/css" rel="stylesheet" href="/static/css/bootstrap-theme-3.1.1.min.css" />
<link type="text/css" rel="stylesheet" href="/static/css/layout.main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.responsive.css" />
<link type="text/css" rel="stylesheet" href="/static/css/main.quickfix.css" />

<!-- /styles -->
{% endblock %}

<!-- favicons -->
<link rel="shortcut icon" href="/static/ico/favicon.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/static/ico/favicon.png">
<!-- /favicons -->

<!-- scripts -->
<script src="/static/js/libs/modernizr-2.8.2.min.js"></script>
<!--[if lt IE 9]><script src="/static/js/libs/respond-1.4.2.min.js"></script><![endif]-->
<!-- /scripts -->

</head>
<body>

  <!-- Wrap all page content here -->
  <div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HSWEB1.0</a>



        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li {% if request.endpoint == 'views.dashboard' %} class="active" {% endif %}><a href="{{ url_for('views.dashboard') }}">Dashboard</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle"data-toggle="dropdown">Reports<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{{ url_for('views.report_listreadings') }}">Log</a></li>
                
                
                <li><a href="{{ url_for('views.report_grafics') }}">Grafics</a></li>
                <li class="divider"></li>
                
                <li><a href="{{ url_for('views.export')}}">Export logs</a></li>
                <li><a>Export data</a></li>
                
             </ul>
            </li>

            <li {% if request.endpoint == 'views.about1' %} class="active" {% endif %}><a href="{{ url_for('views.about1') }}">About</a></li>
            
            <li class="dropdown">
              <a class="dropdown-toggle"data-toggle="dropdown">System<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li {% if request.endpoint == 'views.system' %} class="active" {% endif %}><a href="{{ url_for('system.system_info') }}">System Monitor</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Management</li>
                <li><a href="{{ url_for('system.srvmng',option=1)}}">Reboot</a></li>
                <li><a href="{{ url_for('system.srvmng',option=0)}}">Shutdown</a></li>
                <li><a href="{{ url_for('webapp_auth.show_users',page_num=1)}}">Users</a></li>
                <li><a href="{{ url_for('webapp_auth.user_logs')}}">Stats</a></li>
                <li><a href="{{ url_for('wst.webstreaming_func')}}">test</a></li>
              </ul>
           </li>
            
            
            
            
            
            
          </ul>
          <ul class="nav navbar-nav pull-right">
            {% block sign %}
            {% if current_user.is_authenticated : %}
               
                <li><a href="{{ url_for('webapp_auth.logout') }}">Hi,{{current_user.username}} (logout) </a>   </li>          
                <li><a href="{{ url_for('webapp_auth.edit_user') }}">profile </a>   </li> 
                
            {% else :%}
            
                <li><a href="{{ url_for('webapp_auth.register') }}">Signup</a></li>
                <li><a href="{{ url_for('webapp_auth.login') }}">Login</a></li>
            {% endif %}
      
            
            {% endblock %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- Begin page content -->
    <main  id="content" role="main" class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-block alert-error fade in">
              <a class="close" data-dismiss="alert">&times;</a>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      {% block content %}
   {% endblock %}

    </main>

  </div>

  <div id="footer">
    <div class="container">
      {% block footer %}
      <p class="dashleft" id="current_endpoint">>> {{ request.endpoint }} </p> <p class="dashcenter" id="label_generated">Generated at:</p> <p class="dashcenter" id="generated"></p>     
      
      <p >HSWEBAPP &copy; All Rights Reserved.</p>
      
      {% endblock %}
    </div>
  </div>
  {% block scripts %}
  
       
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script type="text/javascript" src="/static/js/libs/jquery-3.3.1.min.js"><\/script>')</script>
  <script type="text/javascript" src="/static/js/libs/bootstrap-3.1.1.min.js" defer></script>
  <script type="text/javascript" src="/static/js/plugins.js" defer></script>
  <script type="text/javascript" src="/static/js/script.js" defer></script>
  <!-- Google Analytics - Change UA-XXXXX-X to be your site's ID -->
  <script>
  
  window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  });
  
  
  </script>
 {% endblock %}
  
</body>
</html>